spring.application.name=VideoManager

server.port=28800

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=0987654321

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.show_sql=true

spring.mvc.hiddenmethod.filter.enabled=true

spring.flyway.url=jdbc:postgresql://localhost:5432/postgres
spring.flyway.password=0987654321
spring.flyway.user=postgres

jwt_secret = SECRET_recommended_length_is_64_characters
jwt_expiration_access = 1440
jwt_expiration_refresh = 52560000

jwt.cookie-token-key = {"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}

access-token-key={"kty":"oct","k":"hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI"}
refresh-token-key={"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}




logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
logging.level.org.springframework.security.access.intercept=TRACE
logging.level.org.springframework.security.authentication=TRACE

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=DEBUG

#spring.web.resources.static-locations = file:/C:/Users/Petr/git/video-manager-0/build
spring.web.resources.static-locations = file:/C:/Users/Petr/git/ZubrilkaEnglish-private-/VideoManager/src/main/resources/static/video-manager-client/dist/
