apiVersion: v1
kind: Service
metadata:
  #имя сервиса будет ip адресом сервиса
  name: {{.Chart.Name}}-{{.Release.Name}}-clusterip
  labels:
    app: {{.Chart.Name}}-{{.Release.Name}}
spec:
  selector:
    app: {{.Chart.Name}}-{{.Release.Name}}
  ports:
    - port: 80 #сюда будет приходить трафик
      targetPort: 28700 #туда будет отправляться трафик
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Chart.Name}}-{{.Release.Name}}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{.Chart.Name}}-{{.Release.Name}}-clusterip
                port:
                  number: 80
            path: /ze-app
            pathType: Prefix