apiVersion: v1
kind: Service
metadata:
  #имя сервиса будет ip адресом сервиса
  name: {{.Chart.Name}}-{{.Release.Name}}-clusterip
  labels:
    app: {{.Chart.Name}}-{{.Release.Name}}
spec:
  selector:
    app: {{.Chart.Name}}-{{.Release.Name}}
  ports:
    - port: 80 #сюда будет приходить трафик
      targetPort: 28700 #туда будет отправляться трафик
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Chart.Name}}-{{.Release.Name}}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - 598224.cloud4box.ru
      secretName: app-tls
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{.Chart.Name}}-{{.Release.Name}}-clusterip
                port:
                  number: 80
            path: {{ .Values.env.CONTEXT_PATH }}
            pathType: Prefix