CREATE TABLE Person(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email varchar(100) UNIQUE NOT NULL,
    password varchar NOT NULL,
    short_name varchar(100),
    role varchar(100) NOT NULL,
    created_at timestamp
);

CREATE TABLE Word(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    foreign_word varchar(400)NOT NULL,
    transcription varchar(100),
    translation varchar(400)NOT NULL,
    description varchar(400),
    topic varchar(50),
    link_voice varchar(50),
    link_image varchar(50),
    sorting_value integer DEFAULT 0,
    version_update integer DEFAULT 0
);


-- //////////////эти два вызова идут вместе/////////////////
CREATE TABLE properties(
    key varchar(100)UNIQUE NOT NULL,
    value varchar(200)
);
INSERT INTO properties(key,value) VALUES ('dictionary_version',0);