version: '3.8'

services:
  ze_db_postgres:
    image: postgres:14.3-alpine
    restart: always
    container_name: ze_db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=testPassword
      - POSTGRES_USER=postgres
    volumes:
      - ze_db_postgres:/var/lib/postgresql/data/
    networks:
      - ze_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ze_app:
    container_name: ze_app
    image: kmnpetr/ze-app:1.1.9
    restart: always
    ports:
      - "28700:28700"
    environment:
      spring.r2dbc.url: "r2dbc:postgresql://ze_db_postgres:5432/postgres"
      spring.r2dbc.password: "testPassword"
      spring.r2dbc.username: "postgres"
      jwt_secret: "simpleSecret"
    networks:
      - ze_network
    depends_on:
      ze_db_postgres:
        condition: service_healthy

volumes:
  ze_db_postgres:

networks:
  ze_network:
    driver: bridge