version: '3.8'

services:
  ze-db-postgres:
    image: postgres:14.3-alpine
    restart: always
    container_name: ze-db-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${BD_PASSWORD}
      - POSTGRES_USER=${BD_USER}
    volumes:
      - ze-db-postgres:/var/lib/postgresql/data/
    networks:
      - ze_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ze_app:
    container_name: ze_app
    image: kmnpetr/ze-app:${TAG_IMAGE}
    restart: always
    ports:
      - "28700:28700"
    environment:
      spring.r2dbc.url: "r2dbc:postgresql://ze-db-postgres:5432/postgres"
      spring.r2dbc.password: ${BD_PASSWORD}
      spring.r2dbc.username: ${BD_USER}
      jwt_secret: ${JWT_SECRET}
    networks:
      - ze_network
    depends_on:
      ze-db-postgres:
        condition: service_healthy

volumes:
  ze-db-postgres:

networks:
  ze_network:
    driver: bridge