server.port=28800

#it's all because of Helm. The symbol "-" is not valid.
spring.webflux.base-path=${CONTEXT_PATH}
CONTEXT_PATH=/ze-auth


spring.r2dbc.url=r2dbc:postgresql://<host>:5432/<username>
spring.r2dbc.password=<password>
spring.r2dbc.username=<username>


#test jwt_secret
jwt_secret = SECRET