
annotations:
  test: ok

replicas: 1

image:
  repository: kmnpetr/ze-app
  tag: test

port: 28700

resources:
  requests:
    cpu: 150
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 150Mi


env:
  MYSQL_PORT: 3306
  MYSQL_USER: root