annotations:
  test: ok
replicas: 1
image:
  repository: kmnpetr/ze-app
  tag: test
port: 28700
resources:
  requests:
    cpu: 250m
    memory: 400Mi
  limits:
    cpu: 350m
    memory: 500Mi
env:
  spring.datasource.url: "jdbc:postgresql://608686.cloud4box.ru:5432/postgres"
  spring.datasource.password: "CFdZZclszCTaUse"

serviceNodePort:
  port: 80
  targetPort: 28700
  nodePort: 30000
