server.port=28700
server.servlet.context-path=${CONTEXT_PATH}
#it's all because of Helm
CONTEXT_PATH=/ze-app

spring.datasource.driver-class-name=org.postgresql.Driver
#test url
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#test username
spring.datasource.username=postgres
#test password
spring.datasource.password=password

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.show_sql=true

#spring.mvc.hiddenmethod.filter.enabled=true

#test jwt_secret
jwt_secret = SECRET