version: '3.5'

services:
  ze_app:
    container_name: ze_app
    image: kmnpetr/ze-app:test
    ports:
      - "28700:28700"
    environment:
      spring.datasource.url: "jdbc:postgresql://608686.cloud4box.ru:5432/postgres"
      spring.datasource.password: "CFdZZclszCTaUse"
    networks:
      - ze_network

#  ze_db:
#    image: postgres:14.3-alpine
#    restart: always
#    container_name: ze_db
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=
#      - POSTGRES_USER=
#    volumes:
#      - ze_db:/var/lib/postgresql/data/
#    networks:
#      - ze_network

#volumes:
#  ze_db:

networks:
  ze_network:
    driver: bridge
