#server.port=28700
server.port=8443
server.ssl.enabled = true
server.ssl.key-store=/keys/live/zubrilka-english.com/keystore.p12
server.ssl.key-store-password=password
server.ssl.key-password=password

CONTEXT_RELOAD_KEY = CONTEXT_RELOAD_KEY

##it's all because of Helm. The symbol "-" is not valid.
#spring.webflux.base-path=${CONTEXT_PATH}
#CONTEXT_PATH=/ze-app

#logging.level.org.springframework.data.r2dbc=DEBUG

spring.r2dbc.url=r2dbc:postgresql://<host>:5432/<username>
spring.r2dbc.password=<password>
spring.r2dbc.username=<username>

jwt_secret = SECRET


#for local development, it is better to use voicePathFolder = src/main/resources/voice/
voicePathFolder = /voice/


spring.flyway.url=jdbc:postgresql://<host>:5432/<username>
spring.flyway.password=<password>
spring.flyway.user=<username>

#metrics
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=ze-app
management.metrics.distribution.percentiles-histogram.http.server.requests=true

management.zipkin.tracing.endpoint=http://172.17.0.1:9411/api/v2/span
#??? ????? ????? 0.1 ????????????
management.tracing.sampling.probability=1.0

LOKI = http://loki:3100
