#server.port=28700

#it's all because of Helm. The symbol "-" is not valid.
spring.webflux.base-path=${CONTEXT_PATH}
CONTEXT_PATH=/ze-app

#logging.level.org.springframework.data.r2dbc=DEBUG

spring.r2dbc.url=r2dbc:postgresql://<host>:5432/<username>
spring.r2dbc.password=<password>
spring.r2dbc.username=<username>

#test jwt_secret
jwt_secret = SECRET


#for local development, it is better to use voicePathFolder = src/main/resources/voice/
voicePathFolder = /voice/


spring.flyway.url=jdbc:postgresql://<host>:5432/<username>
spring.flyway.password=<password>
spring.flyway.user=<username>

server.port=8443
server.ssl.enabled = true
server.ssl.key-store=/keys/live/zubrilka-english.com/keystore.p12
server.ssl.key-store-password=password
server.ssl.key-password=password

