apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-{{.Release.Name}}
  labels:
    app: {{.Chart.Name}}-{{.Release.Name}}
{{- if .Values.annotations}}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas | default 1}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}-{{.Release.Name}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          ports:
            - containerPort: {{ .Values.port}}
          resources:
{{toYaml .Values.resources | indent 12}}
          env:
            - name: "spring.datasource.url"
              value: {{ .Values.env.db_url }}
            - name: "spring.datasource.password"
              value: {{ .Values.env.db_password }}
            - name: "jwt_secret"
              value: {{ .Values.env.jwt_secret }}
          {{- if .Values.other_env}}
          {{- range $key, $val := .Values.other_env }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }}