apiVersion: v1
kind: Service
metadata:
  #имя сервиса будет ip адресом сервиса
  name: {{.Chart.Name}}-{{.Release.Name}}-nodeport
  labels:
    app: {{.Chart.Name}}-{{.Release.Name}}
spec:
  selector:
    app: {{.Chart.Name}}-{{.Release.Name}}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.serviceNodePort.port }}
      targetPort: {{ .Values.serviceNodePort.targetPort }}
      nodePort: {{ .Values.serviceNodePort.nodePort }}