version: '3.8'

services:
  nginx:
    image: nginx:1.27.3
    container_name: nginx-dev-proxy
    ports:
      - "45777:45777"
    volumes:
      - "C:/Users/Petr/ssl:/etc/nginx/ssl:ro"
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped