version: '3.8'

services:
  certbot:
    container_name: certbot
    build: .
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
#    certbot renew --dry-run   для перезаписи тестовая симуляция
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/sertbot:/etc/letsencrypt" #ключи сертификаты и прочие конфиги бота. скрипты по пути ......
      - "/sertbot/lib:/var/lib/letsencrypt" # просто пустая наверное
      - "/sertbot/log:/var/log"
