version: '3.8'

services:
  certbot:
    build:
      context: .
#      args:
#        DOMAIN_NAME: ${DOMAIN_NAME}
#    environment:
#      DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "80:80"
    volumes:
      - "/sertbot:/etc/letsencrypt" #ключи сертификаты и прочие конфиги бота. скрипты по пути ......
      - "/sertbot/lib:/var/lib/letsencrypt" # просто пустая наверное
