version: '3.8'

services:
  certbot:
    container_name: certbot
    build: .
#      args:
#        DOMAIN_NAME: ${DOMAIN_NAME}
#    environment:
#      DOMAIN_NAME: ${DOMAIN_NAME}
    entrypoint: /usr/local/bin/script.sh
#    command:
#      - certbot certonly
#        --email kmn.petrichenko@yandex.ru -d 608686777.cloud4box.ru
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/sertbot:/etc/letsencrypt" #ключи сертификаты и прочие конфиги бота. скрипты по пути ......
      - "/sertbot/lib:/var/lib/letsencrypt" # просто пустая наверное
      - "/sertbot/log:/var/log"
