on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory
        run: cd ZubrilkaEnglish_server

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Mvn Clean Package
        run: mvn -f ZubrilkaEnglish_server clean package

      - name: Mvn Clean Package
        run: docker build -t kmnpetr/ze ./ZubrilkaEnglish_server

      - name: Display a message
        run: echo "Hello from GitHub Actions"
