name: Deploy_App
on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BD_URL: ${{ secrets.BD_URL }}
      BD_PASSWORD: ${{ secrets.BD_PASSWORD }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Сhanging the application version
        run: |
          File="./ZubrilkaEnglish_server/pom.xml"
          
          sudo apt-get install -y xmlstarlet
          
          Version=$(xmlstarlet sel -N p=http://maven.apache.org/POM/4.0.0 -t -v "/p:project/p:version" $File)
          echo "Old version: ${Version}"
          IFS='.' read -r -a arr <<< "$Version"
          ((arr[2]+=1))
          NewVersion=$(IFS="."; echo "${arr[*]}")
          echo "NewVersion: ${NewVersion}"
          
          xmlstarlet ed -L -N p=http://maven.apache.org/POM/4.0.0 -u "/p:project/p:version" -v $NewVersion $File
          
          git add .
          git commit -m "[skip ci] Workwlow modification: App-version = $NewVersion"
          #для работы коммита требуется настроить name и email для гита(смотреть шаг Setup git config)
          #а также дать разрешение на запись через веб страницу github (репозиторий>>Settings>>Actions>>General>>Workflow permissions)
          git push origin main
          
          echo "TAG_IMAGE=${NewVersion}" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Mvn Clean Package
        run: mvn -f ./ZubrilkaEnglish_server clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build And Push
        run: |
          ImageName="ze-app:${TAG_IMAGE}"
          docker build -t kmnpetr/$ImageName ./ZubrilkaEnglish_server
          docker push kmnpetr/$ImageName

      - name: Git Pull On Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            git -C /home/ZubrilkaEnglish-private- pull

      - name: Helm Upgrade
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: TAG_IMAGE, BD_URL, BD_PASSWORD
          script: |
            helm uninstall dev || true
            helm upgrade --install dev \
            /home/ZubrilkaEnglish-private-/ZubrilkaEnglish_server/test-helm/ \
            --set image.tag=$(echo $TAG_IMAGE) \
            --set env:spring.datasource.url="$(echo $BD_URL)" \
            --set env:spring.datasource.password="$(echo $BD_PASSWORD)" \
            --debug \
            --atomic \
            --timeout 300s