name: Deploy_App
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Сhanging the application version
        run: |
          File="./ZubrilkaEnglish_server/pom.xml"
          
          sudo apt-get install -y xmlstarlet
          
          Version=$(xmlstarlet sel -N p=http://maven.apache.org/POM/4.0.0 -t -v "/p:project/p:version" $File)
          echo "Old version: ${Version}"
          IFS='.' read -r -a arr <<< "$Version"
          #если в следующей строке возникнет ошибка,возможно скрипт пытается прибавить 1 к нулю
          ((arr[2]++))
          NewVersion=$(IFS="."; echo "${arr[*]}")
          echo "NewVersion: ${NewVersion}"
          
          xmlstarlet ed -L -N p=http://maven.apache.org/POM/4.0.0 -u "/p:project/p:version" -v $NewVersion $File
          
          git add .
          git commit -m "[skip ci] Workwlow modification: App-version = $NewVersion"
          git push origin main

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17


      - name: Mvn Clean Package
        run: mvn -f ./ZubrilkaEnglish_server clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build And Push
        run: |
          Version=$(xmlstarlet sel -N p=http://maven.apache.org/POM/4.0.0 -t -v "/p:project/p:version" $File)
          ImageName="ze-app:${Version}"
          docker build -t kmnpetr/$ImageName ./ZubrilkaEnglish_server
          docker push kmnpetr/$ImageName

#
#      - name: Stop APP on server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          script: |
#            docker ps -a || true
#            docker compose -f /home/ze/docker-compose.yml down || true
#            docker images || true
#            docker rmi kmnpetr/ze || true
#            mkdir /home/ze/ || true
#
#        #короче эти два шага лучше использовать вместе и лишний раз не трогать, а то неадекватно вести себя начинают
#      - name: Checkout
#        uses: actions/checkout@v2
#
#        #короче эти два шага лучше использовать вместе и лишний раз не трогать, а то неадекватно вести себя начинают
#      - name: Send docker-compose.yml to server
#        uses: kostya-ten/ssh-server-deploy@v4
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          port: 22
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          scp_source: ./ZubrilkaEnglish_server/docker-compose.yml
#          scp_target: /home/ze
#          before_script: |
#            echo "Start Deploy"
#          after_script: |
#            echo "And Deploy"
#
#      - name: Up docker-compose.yml
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          script: |
#            docker compose -f /home/ze/docker-compose.yml up -d