name: Test-App
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Mvn Clean Package
        run: mvn -f ./ZubrilkaEnglish_server clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build And Push
        run: |
          docker build -t kmnpetr/ze-app:test ./ZubrilkaEnglish_server
          docker push kmnpetr/ze-app:test

      - name: Git Pull On Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            git -C /home/ZubrilkaEnglish-private- pull

      - name: Up docker-compose.yml
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker compose -f /home/ZubrilkaEnglish-private-/ZubrilkaEnglish_server/docker-compose.yml down || true
            docker rmi kmnpetr/ze-app:test || true
            docker compose -f /home/ZubrilkaEnglish-private-/ZubrilkaEnglish_server/docker-compose.yml up -d